# Generated by Django 3.1.6 on 2021-10-29 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appel_Offre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, null=True)),
                ('detail', models.CharField(max_length=800, null=True)),
                ('duree', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Secteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='postulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=800, null=True)),
                ('budget', models.FloatField(default=0, null=True)),
                ('duree', models.CharField(max_length=20, null=True)),
                ('nom_responsable', models.CharField(max_length=20, null=True)),
                ('file', models.FileField(upload_to='uploads/')),
                ('titre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.appel_offre')),
            ],
        ),
        migrations.AddField(
            model_name='appel_offre',
            name='secteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.secteur'),
        ),
    ]
